### PR TITLE
Update sitemap plugin to include English pages from subdirectories

### PR DESCRIPTION
**Pull request by ghost1542**
Your latest HTML diff made me realize that the sitemap plugin wasn't including static English pages from subdirectories, so this pull request should fix that.

sitemap.xml diff:
http://bitcointest3.us.to/diff.html

This plugin does not include the blog posts either in fact but I didn't have enough time to fix it. I wonder if it wouldn't be less error prone if there was a reliable way to get the list of all page rendered by Jekyll through jekyll itself. I think I remember trying this approach but eventually giving up due to many issues.

### CODE REVIEW

**Comment by harding** [comment]
Did a quick search and found this: http://davidensinger.com/2013/11/building-a-better-sitemap-xml-with-jekyll/

I tried his code verbatim and it seemed to grab everything just fine.  If you'd like, I'll follow up with a full implementation and a regression test.

**Comment by ghost1542** [comment]
I think you may have to update the templates plugin to either generate alternate hreflang attributes in the pages directly instead of the sitemap, or create a global site variable available to liquid, so you can generate them in the sitemap.xml without further help from a plugin.

**Comment by harding** [comment]
@saivann ok.  I'll play around with it this afternoon.  Thanks!

**Comment by ghost1542** [comment]
@harding Thanks for looking at it! If that works, that seems like a much better way to generate sitemap.xml.

**Comment by ghost1542** [comment]
Additional note; Here's a good way to ignore all non-html stuff like css, js files and the sitemap.xml file itself.

`{% capture extension %}{{ page.url | split:"." | last }}{% endcapture %}{% unless extension != "html" %}`

**Comment by harding** [comment]
I messed around with this for a while and got reasonably good results with https://github.com/harding/bitcoin.org/commit/3e7dc79544a6318b1e745b32ce7312bcc277faeb, but perfecting it seems like it will have higher code complexity than the current plugin, so I'm just going to merge this PR for now.  If I ever get really bored, I'll look at it again.

Thanks.

**Comment by ghost1542** [comment]
Thanks! I may try to work on it eventually too.

**Pull request merged**
